/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Mjolnir.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Mjolnir.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.302, 0.051, -0.001]} scale={0.006}>
        <group position={[50.347, -58.713, 0.16]} rotation={[-Math.PI / 2, -0.007, Math.PI]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.HammerHandle_HP_Hammer_0.geometry} material={materials.Hammer} position={[0, -15.554, 0]} />
            <mesh geometry={nodes.HammerKnob_HP_Hammer_0.geometry} material={materials.Hammer} position={[0, -170.436, 0]} />
            <mesh geometry={nodes.HammerBand_HP_Hammer_0.geometry} material={materials.Hammer} position={[10.374, -188.862, 0]} />
            <mesh geometry={nodes.HammerHeadTop_HP_Hammer_0.geometry} material={materials.Hammer} position={[-24.95, 26.349, 0]} />
            <mesh geometry={nodes.HammerHead_HP_Hammer_0.geometry} material={materials.Hammer} position={[-24.95, 26.349, 0]} />
            <mesh geometry={nodes.Ornament_01_HP000_Ornaments_0.geometry} material={materials.Ornaments} position={[113.856, 245.222, 69.274]} rotation={[0, -0.994, Math.PI / 2]} />
            <mesh geometry={nodes.Ornament_01_HP001_Ornaments_0.geometry} material={materials.Ornaments} position={[-112.881, 245.222, 67.594]} rotation={[0, 1.023, Math.PI / 2]} />
            <mesh geometry={nodes.Ornament_01_HP002_Ornaments_0.geometry} material={materials.Ornaments} position={[-114.181, 245.222, -69.487]} rotation={[Math.PI, 0.992, -Math.PI / 2]} />
            <mesh geometry={nodes.Ornament_01_HP003_Ornaments_0.geometry} material={materials.Ornaments} position={[112.285, 245.222, -67.669]} rotation={[-Math.PI, -1.013, -Math.PI / 2]} />
            <mesh geometry={nodes.Ornament_01_HP004_Ornaments_0.geometry} material={materials.Ornaments} position={[112.702, 312.822, 0.018]} rotation={[-Math.PI / 2, -1.013, -Math.PI / 2]} />
            <mesh geometry={nodes.Ornament_01_HP005_Ornaments_0.geometry} material={materials.Ornaments} position={[-114.197, 314.894, 0.018]} rotation={[-Math.PI / 2, 1.009, -Math.PI / 2]} />
            <mesh geometry={nodes.Ornament_01_HP006_Ornaments_0.geometry} material={materials.Ornaments} position={[-112.945, 176.835, 0.018]} rotation={[Math.PI / 2, 1.003, Math.PI / 2]} />
            <mesh geometry={nodes.Ornament_01_HP007_Ornaments_0.geometry} material={materials.Ornaments} position={[113.851, 174.011, 0.018]} rotation={[Math.PI / 2, -1.001, Math.PI / 2]} />
          </group>
        </group>
      </group>
      <directionalLight intensity={2} decay={2} />
    </group>
  )
}

useGLTF.preload('/Mjolnir.glb')
